# Generated by Django 4.2.7 on 2023-11-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('duedate', models.DateField()),
                ('duetime', models.TimeField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
